### ISSUE TITLE
TypeError: callback is not a function when trying to acknowledge a message

### ISSUE THREAD

**Issue by victor-solvethex** [onify/fake-amqplib#2]
I'm trying to acknowledge a message with `channel.ack(msg)` but it fails for some reason using your library on tests

```
TypeError: callback is not a function

      at confirmCallback (node_modules/@onify/fake-amqplib/index.js:270:11)
      at onConsumeMessage (node_modules/@onify/fake-amqplib/index.js:265:20)
      at eventCallback (node_modules/smqp/dist/src/Broker.js:478:9)
      at consume (node_modules/smqp/dist/src/Queue.js:573:5)
      at Object.push (node_modules/smqp/dist/src/Queue.js:546:7)
      at consumeNext (node_modules/smqp/dist/src/Queue.js:146:16)
      at Object.queueMessage (node_modules/smqp/dist/src/Queue.js:125:28)
      at publishToQueue (node_modules/smqp/dist/src/Exchange.js:123:11)
      at node_modules/smqp/dist/src/Exchange.js:103:11
          at Array.forEach (<anonymous>)
      at topic (node_modules/smqp/dist/src/Exchange.js:101:15)
      at consume (node_modules/smqp/dist/src/Queue.js:573:5)
      at Object.push (node_modules/smqp/dist/src/Queue.js:546:7)
      at consumeNext (node_modules/smqp/dist/src/Queue.js:146:16)
      at Object.queueMessage (node_modules/smqp/dist/src/Queue.js:125:28)
      at Object.publish (node_modules/smqp/dist/src/Exchange.js:76:26)
```

**Comment by victor-solvethex** [comment]
My code:

```typescript
it('should publish messages to a previously created queue', async (done) => {
		const chann = await rabbitService.getChannel()
		chann.consume(
			'cool_queue',
			(msg: any) => {
				expect(msg).toBeTruthy()
				if (msg) expect(msg.content.toString()).toBe('Hello, World')
                                chann.ack(msg)
				done()
			},
			{ consumerTag: 'yey' }
		)
	})
```

**Comment by victor-solvethex** [comment]
Okey I found the error, I was trying to use ack() on an already acknowledged message. I was using ConfirmChannels instead of normal Channels

**Comment by paed01** [comment]
So the issue is solved?
